import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Nested Dynamic Segment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <h2>Nested Dynamic Segment</h2>
          <p>check the urls</p>
          <ul>
            <li>
              <Link href="/en">ENG (Dynamic Segment route [lang])</Link>
            </li>
            <li>
              <Link href="/pl">PL (Dynamic Segment route [lang])</Link>
            </li>
            <li>
              <Link href="/en/test">
                English Sub Page (Dynamic Segment route [lang]/test)
              </Link>
            </li>
            <li>
              <Link href="/pl/test">
                PL Sub Page (Dynamic Segment route [lang]/test)
              </Link>
            </li>
          </ul>
          <hr />
        </div>
        {children}
      </body>
    </html>
  );
}
